import type { Question } from "../types";

const c = (options: string[], correctIndex: number) =>
  ({ kind: "choice", options, correctIndex }) as const;
const n = (value: number, tolerance = 0) =>
  ({ kind: "numeric", value, tolerance }) as const;
const seq = (...items: (string | number)[]) =>
  ({ kind: "text-sequence", items: items.map(String) }) as const;

export const numericalQuestions: Question[] = [
  {
    id: "num-001",
    category: "numerical",
    difficulty: 1,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 4, 6, 8, "?"),
    answer: c(["10", "9", "12", "16"], 0),
    explanation: "The series increases by 2 each step.",
  },
  {
    id: "num-002",
    category: "numerical",
    difficulty: 1,
    prompt: "Which number continues the series?",
    stimulus: seq(3, 6, 12, 24, "?"),
    answer: c(["48", "36", "42", "50"], 0),
    explanation: "Each term doubles.",
  },
  {
    id: "num-003",
    category: "numerical",
    difficulty: 2,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 4, 9, 16, "?"),
    answer: c(["25", "20", "24", "32"], 0),
    explanation: "These are the perfect squares 1², 2², 3², 4², 5².",
  },
  {
    id: "num-004",
    category: "numerical",
    difficulty: 2,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 3, 5, 8, 12, "?"),
    answer: c(["17", "16", "18", "20"], 0),
    explanation: "The gaps grow by one: +1, +2, +3, +4, +5.",
  },
  {
    id: "num-005",
    category: "numerical",
    difficulty: 2,
    prompt: "Which number continues the series?",
    stimulus: seq(81, 27, 9, 3, "?"),
    answer: c(["1", "0", "2", "1.5"], 0),
    explanation: "Each term is divided by 3.",
  },
  {
    id: "num-006",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 1, 2, 3, 5, 8, "?"),
    answer: c(["13", "11", "12", "16"], 0),
    explanation: "Fibonacci: each term is the sum of the two before it.",
  },
  {
    id: "num-007",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 6, 12, 20, 30, "?"),
    answer: c(["42", "40", "36", "44"], 0),
    explanation: "The terms are n(n + 1): 1·2, 2·3, 3·4, 4·5, 5·6, 6·7.",
  },
  {
    id: "num-008",
    category: "numerical",
    difficulty: 2,
    prompt: "Which number continues the series?",
    stimulus: seq(7, 14, 28, 56, "?"),
    answer: c(["112", "84", "98", "108"], 0),
    explanation: "Each term doubles.",
  },
  {
    id: "num-009",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(100, 96, 88, 72, "?"),
    answer: c(["40", "56", "48", "64"], 0),
    explanation: "The subtractions double: −4, −8, −16, −32.",
  },
  {
    id: "num-010",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(3, 7, 16, 35, 74, "?"),
    answer: c(["153", "148", "160", "139"], 0),
    explanation: "Each term is double the previous plus a step that grows: ×2+1, ×2+2, ×2+3, ×2+4, then ×2+5.",
  },
  {
    id: "num-011",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 2, 6, 24, 120, "?"),
    answer: c(["720", "600", "480", "840"], 0),
    explanation: "Factorials: each term is multiplied by the next integer.",
  },
  {
    id: "num-012",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 5, 11, 23, 47, "?"),
    answer: c(["95", "94", "96", "93"], 0),
    explanation: "Each term is double the previous plus 1.",
  },
  {
    id: "num-013",
    category: "numerical",
    difficulty: 5,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 3, 7, 15, 31, "?"),
    answer: c(["63", "62", "47", "64"], 0),
    explanation: "The terms are 2ⁿ − 1: 1, 3, 7, 15, 31, 63.",
  },
  {
    id: "num-014",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 3, 5, 7, 11, 13, "?"),
    answer: c(["17", "15", "16", "19"], 0),
    explanation: "Consecutive prime numbers.",
  },
  {
    id: "num-015",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(6, 12, 21, 33, 48, "?"),
    answer: c(["66", "63", "69", "72"], 0),
    explanation: "The gaps grow by 3: +6, +9, +12, +15, +18.",
  },
  {
    id: "num-016",
    category: "numerical",
    difficulty: 2,
    prompt:
      "A jacket costs 80 and is reduced by 25% in a sale. What is the sale price?",
    answer: n(60),
    explanation: "25% of 80 is 20, so the price falls to 60.",
  },
  {
    id: "num-017",
    category: "numerical",
    difficulty: 3,
    prompt:
      "A price of 100 rises by 20% and then falls by 20%. What is the final price?",
    answer: n(96),
    explanation:
      "100 → 120 → 96. The fall is applied to the larger amount, so the round trip loses value.",
  },
  {
    id: "num-018",
    category: "numerical",
    difficulty: 3,
    prompt:
      "If 5 machines take 5 minutes to make 5 widgets, how many minutes do 100 machines take to make 100 widgets?",
    answer: n(5),
    explanation:
      "Each machine makes one widget in 5 minutes, and the machines work in parallel.",
  },
  {
    id: "num-019",
    category: "numerical",
    difficulty: 2,
    prompt:
      "Two numbers add up to 30 and differ by 8. What is the larger number?",
    answer: n(19),
    explanation: "(30 + 8) / 2 = 19.",
  },
  {
    id: "num-020",
    category: "numerical",
    difficulty: 4,
    prompt:
      "A car travels 120 km at 60 km/h, then 120 km at 40 km/h. What is its average speed in km/h for the whole journey?",
    answer: n(48),
    explanation:
      "The journey takes 2 + 3 = 5 hours for 240 km, giving 48 km/h — not the arithmetic mean of 50.",
  },
  {
    id: "num-021",
    category: "numerical",
    difficulty: 4,
    prompt:
      "A bat and a ball cost 1.10 in total. The bat costs 1.00 more than the ball. How many cents does the ball cost?",
    answer: n(5),
    explanation:
      "The ball is 0.05 and the bat 1.05 — a difference of exactly 1.00.",
  },
  {
    id: "num-022",
    category: "numerical",
    difficulty: 2,
    prompt: "What is 15% of 240?",
    answer: n(36),
    explanation: "10% is 24 and 5% is 12, so 15% is 36.",
  },
  {
    id: "num-023",
    category: "numerical",
    difficulty: 4,
    prompt:
      "Pipe A fills a tank in 6 hours and pipe B fills it in 3 hours. How many hours does it take with both pipes open?",
    answer: n(2),
    explanation: "Combined rate is 1/6 + 1/3 = 1/2 of the tank per hour.",
  },
  {
    id: "num-024",
    category: "numerical",
    difficulty: 3,
    prompt:
      "In a class of 40 students the ratio of boys to girls is 3:5. How many girls are there?",
    answer: n(25),
    explanation: "Eight parts of 5 students each; girls take 5 parts = 25.",
  },
  {
    id: "num-025",
    category: "numerical",
    difficulty: 5,
    prompt:
      "The average of five numbers is 12. One number is removed and the average of the remaining four is 13. What was the removed number?",
    answer: n(8),
    explanation: "The totals are 60 and 52, so the removed number is 8.",
  },
  {
    id: "num-026",
    category: "numerical",
    difficulty: 1,
    prompt: "If 3x + 7 = 25, what is x?",
    answer: n(6),
    explanation: "3x = 18, so x = 6.",
  },
  {
    id: "num-027",
    category: "numerical",
    difficulty: 4,
    prompt:
      "A shirt sells for 63 at a 10% loss on its cost price. What was the cost price?",
    answer: n(70),
    explanation: "63 is 90% of the cost, so the cost is 63 / 0.9 = 70.",
  },
  {
    id: "num-028",
    category: "numerical",
    difficulty: 4,
    prompt:
      "1000 is invested at 10% compound interest per year. What is it worth after two years?",
    answer: n(1210),
    explanation: "1000 → 1100 → 1210.",
  },
  {
    id: "num-029",
    category: "numerical",
    difficulty: 2,
    prompt: "Which of these values is the largest?",
    answer: c(["0.71", "0.7", "2/3", "68%"], 0),
    explanation: "0.71 > 0.70 > 0.68 > 0.667.",
  },
  {
    id: "num-030",
    category: "numerical",
    difficulty: 3,
    prompt:
      "A rectangle's length is twice its width and its perimeter is 36. What is its area?",
    answer: n(72),
    explanation: "Width 6, length 12, so the area is 72.",
  },
  {
    id: "num-031",
    category: "numerical",
    difficulty: 5,
    prompt:
      "How many integers from 1 to 100 inclusive are divisible by 3 or by 5?",
    answer: n(47),
    explanation:
      "33 are divisible by 3, 20 by 5 and 6 by both, so 33 + 20 − 6 = 47.",
  },
  {
    id: "num-032",
    category: "numerical",
    difficulty: 2,
    prompt:
      "A recipe for 4 people uses 300 g of flour. How many grams are needed for 7 people?",
    answer: n(525),
    explanation: "75 g per person × 7 = 525 g.",
  },
  {
    id: "num-033",
    category: "numerical",
    difficulty: 1,
    prompt: "Which number continues the series?",
    stimulus: seq(5, 10, 20, 40, "?"),
    answer: c(["80", "60", "70", "45"], 0),
    explanation: "Each term doubles.",
  },
  {
    id: "num-034",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 2, 4, 7, 11, 16, "?"),
    answer: c(["22", "21", "23", "24"], 0),
    explanation: "The gaps grow by one each step: +1, +2, +3, +4, +5, +6.",
  },
  {
    id: "num-035",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(144, 121, 100, 81, "?"),
    answer: c(["64", "72", "49", "60"], 0),
    explanation: "Descending perfect squares: 12², 11², 10², 9², 8².",
  },
  {
    id: "num-036",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 8, 27, 64, "?"),
    answer: c(["125", "100", "128", "216"], 0),
    explanation: "The cubes: 1³, 2³, 3³, 4³, 5³.",
  },
  {
    id: "num-037",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(3, 4, 7, 11, 18, 29, "?"),
    answer: c(["47", "45", "48", "40"], 0),
    explanation: "Each term is the sum of the two before it.",
  },
  {
    id: "num-038",
    category: "numerical",
    difficulty: 5,
    prompt: "Which number continues the series?",
    stimulus: seq(2, 12, 36, 80, 150, "?"),
    answer: c(["252", "240", "245", "260"], 0),
    explanation: "The terms are n³ + n²: 1+1, 8+4, 27+9, 64+16, 125+25, then 216+36.",
  },
  {
    id: "num-039",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(4, 10, 22, 46, 94, "?"),
    answer: c(["190", "188", "192", "186"], 0),
    explanation: "Each term is double the previous plus 2.",
  },
  {
    id: "num-040",
    category: "numerical",
    difficulty: 5,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 4, 27, 256, "?"),
    answer: c(["3125", "625", "1024", "2401"], 0),
    explanation: "Each term is n raised to its own power: 1¹, 2², 3³, 4⁴, 5⁵.",
  },
  {
    id: "num-041",
    category: "numerical",
    difficulty: 2,
    prompt: "Which number continues the series?",
    stimulus: seq(9, 16, 25, 36, "?"),
    answer: c(["49", "45", "48", "42"], 0),
    explanation: "Consecutive squares from 3² upwards.",
  },
  {
    id: "num-042",
    category: "numerical",
    difficulty: 1,
    prompt: "What is 12 × 15?",
    answer: n(180),
    explanation: "12 × 15 = 12 × 10 + 12 × 5 = 120 + 60.",
  },
  {
    id: "num-043",
    category: "numerical",
    difficulty: 3,
    prompt: "A number increased by 40% becomes 84. What was the original number?",
    answer: n(60),
    explanation: "84 ÷ 1.4 = 60.",
  },
  {
    id: "num-044",
    category: "numerical",
    difficulty: 3,
    prompt: "Three consecutive even integers add up to 78. What is the largest of them?",
    answer: n(28),
    explanation: "The middle number is 78 ÷ 3 = 26, so the three are 24, 26 and 28.",
  },
  {
    id: "num-045",
    category: "numerical",
    difficulty: 2,
    prompt: "A train covers 180 km in 2.5 hours. What is its average speed in km/h?",
    answer: n(72),
    explanation: "180 ÷ 2.5 = 72.",
  },
  {
    id: "num-046",
    category: "numerical",
    difficulty: 3,
    prompt: "If 8 workers build a wall in 6 days, how many days would 12 workers of equal speed take?",
    answer: n(4),
    explanation: "The job takes 48 worker-days, so 12 workers need 4 days.",
  },
  {
    id: "num-047",
    category: "numerical",
    difficulty: 5,
    prompt: "A shop marks its goods up by 40% on cost, then advertises 25% off the marked price. What percentage profit on cost does it still make?",
    answer: n(5),
    explanation: "1.40 × 0.75 = 1.05, so 5% above cost.",
  },
  {
    id: "num-048",
    category: "numerical",
    difficulty: 2,
    prompt: "What is 3/8 expressed as a percentage?",
    answer: n(37.5),
    explanation: "3 ÷ 8 = 0.375.",
  },
  {
    id: "num-049",
    category: "numerical",
    difficulty: 4,
    prompt: "The sum of a positive number and its square is 42. What is the number?",
    answer: n(6),
    explanation: "6 + 36 = 42.",
  },
  {
    id: "num-050",
    category: "numerical",
    difficulty: 5,
    prompt: "How many different three-digit numbers can be formed from the digits 1, 2, 3, 4 and 5 if no digit may repeat?",
    answer: n(60),
    explanation: "5 × 4 × 3 = 60.",
  },
  {
    id: "num-051",
    category: "numerical",
    difficulty: 3,
    prompt: "A map is drawn at a scale of 1:50,000. How many kilometres does 4 cm on the map represent?",
    answer: n(2),
    explanation: "4 cm × 50,000 = 200,000 cm = 2 km.",
  },
  {
    id: "num-052",
    category: "numerical",
    difficulty: 2,
    prompt: "The average of 12, 15 and one other number is 14. What is the third number?",
    answer: n(15),
    explanation: "The three must total 42, and 42 − 27 = 15.",
  },
  {
    id: "num-053",
    category: "numerical",
    difficulty: 5,
    prompt: "A tank is three-fifths full. After 24 litres are drained it is one-third full. What is the tank's capacity in litres?",
    answer: n(90),
    explanation: "The 24 litres represent 3/5 − 1/3 = 4/15 of the tank, so the capacity is 24 ÷ (4/15) = 90.",
  },
  {
    id: "num-054",
    category: "numerical",
    difficulty: 2,
    prompt: "What is 20% of 20% of 500?",
    answer: n(20),
    explanation: "20% of 500 is 100, and 20% of 100 is 20.",
  },
  {
    id: "num-055",
    category: "numerical",
    difficulty: 4,
    prompt: "Two ordinary dice are rolled. In how many of the 36 equally likely outcomes do the two faces total exactly 7?",
    answer: n(6),
    explanation: "1+6, 2+5, 3+4, 4+3, 5+2 and 6+1.",
  },
  {
    id: "num-056",
    category: "numerical",
    difficulty: 1,
    prompt: "What is 7 × 8?",
    answer: n(56),
    explanation: "Seven eights are fifty-six.",
  },
  {
    id: "num-057",
    category: "numerical",
    difficulty: 1,
    prompt: "Which number continues the series?",
    stimulus: seq(10, 20, 30, 40, "?"),
    answer: c(["50", "45", "60", "44"], 0),
    explanation: "The series goes up by ten each step.",
  },
  {
    id: "num-058",
    category: "numerical",
    difficulty: 1,
    prompt: "What is half of 46?",
    answer: n(23),
    explanation: "46 ÷ 2 = 23.",
  },
  {
    id: "num-059",
    category: "numerical",
    difficulty: 1,
    prompt: "What is 100 − 37?",
    answer: n(63),
    explanation: "100 − 37 = 63.",
  },
  {
    id: "num-060",
    category: "numerical",
    difficulty: 1,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 3, 5, 7, 9, "?"),
    answer: c(["11", "10", "12", "13"], 0),
    explanation: "The odd numbers in order.",
  },
  {
    id: "num-061",
    category: "numerical",
    difficulty: 2,
    prompt: "A book has 120 pages. You have read a quarter of it. How many pages are left?",
    answer: n(90),
    explanation: "A quarter of 120 is 30, leaving 90.",
  },
  {
    id: "num-062",
    category: "numerical",
    difficulty: 2,
    prompt: "Four pens cost 60 in total. What does one pen cost?",
    answer: n(15),
    explanation: "60 ÷ 4 = 15.",
  },
  {
    id: "num-063",
    category: "numerical",
    difficulty: 3,
    prompt: "Which number continues the series?",
    stimulus: seq(5, 8, 13, 21, 34, "?"),
    answer: c(["55", "47", "50", "58"], 0),
    explanation: "Each term is the sum of the two before it.",
  },
  {
    id: "num-064",
    category: "numerical",
    difficulty: 3,
    prompt:
      "A jacket is reduced by one fifth and now costs 48. What was its original price?",
    answer: n(60),
    explanation: "48 is four fifths of the original, so the original is 48 ÷ 0.8 = 60.",
  },
  {
    id: "num-065",
    category: "numerical",
    difficulty: 4,
    prompt: "Which number continues the series?",
    stimulus: seq(3, 6, 18, 72, "?"),
    answer: c(["360", "288", "216", "144"], 0),
    explanation: "The multiplier grows each step: ×2, ×3, ×4, then ×5.",
  },
  {
    id: "num-066",
    category: "numerical",
    difficulty: 4,
    prompt:
      "Five consecutive whole numbers add up to 100. What is the smallest of them?",
    answer: n(18),
    explanation:
      "The middle number is 100 ÷ 5 = 20, so the five are 18, 19, 20, 21 and 22.",
  },
  {
    id: "num-067",
    category: "numerical",
    difficulty: 5,
    prompt: "Which number continues the series?",
    stimulus: seq(1, 2, 5, 26, "?"),
    answer: c(["677", "676", "52", "130"], 0),
    explanation: "Each term is the previous one squared, plus one.",
  },
  {
    id: "num-068",
    category: "numerical",
    difficulty: 5,
    prompt: "How many two-digit numbers have digits that add up to exactly 9?",
    answer: n(9),
    explanation:
      "18, 27, 36, 45, 54, 63, 72, 81 and 90 — nine of them. 09 is not a two-digit number.",
  },
  {
    id: "num-069",
    category: "numerical",
    difficulty: 5,
    prompt:
      "A clock loses four minutes every hour. It is set correctly at 12:00. What time does it show when the real time is 6:00?",
    answer: c(["5:36", "5:24", "5:56", "6:24"], 0),
    explanation: "Over six hours it loses 24 minutes, so it shows 5:36.",
  },
];
