import type { Question } from "../types";

const c = (options: string[], correctIndex: number) =>
  ({ kind: "choice", options, correctIndex }) as const;

export const verbalQuestions: Question[] = [
  {
    id: "ver-001",
    category: "verbal",
    difficulty: 1,
    prompt: "Bird is to nest as bee is to:",
    answer: c(["Hive", "Honey", "Flower", "Swarm"], 0),
    explanation: "The relationship is 'creature to the structure it lives in'.",
  },
  {
    id: "ver-002",
    category: "verbal",
    difficulty: 1,
    prompt: "Which word is the odd one out?",
    answer: c(["Oak", "Rose", "Tulip", "Daisy"], 0),
    explanation: "The other three are flowers; an oak is a tree.",
  },
  {
    id: "ver-003",
    category: "verbal",
    difficulty: 2,
    prompt: "Doctor is to hospital as teacher is to:",
    answer: c(["School", "Student", "Lesson", "Book"], 0),
    explanation: "The relationship is 'professional to workplace'.",
  },
  {
    id: "ver-004",
    category: "verbal",
    difficulty: 2,
    prompt: "Which word is closest in meaning to 'candid'?",
    answer: c(["Frank", "Secretive", "Careless", "Hostile"], 0),
    explanation: "Candid means open and straightforward in speech.",
  },
  {
    id: "ver-005",
    category: "verbal",
    difficulty: 2,
    prompt: "Which word is most nearly the opposite of 'scarce'?",
    answer: c(["Abundant", "Costly", "Fragile", "Hidden"], 0),
    explanation: "Scarce means in short supply; abundant is its opposite.",
  },
  {
    id: "ver-006",
    category: "verbal",
    difficulty: 3,
    prompt: "'Ephemeral' most nearly means:",
    answer: c(["Short-lived", "Weightless", "Mysterious", "Repeated"], 0),
    explanation: "Ephemeral describes something lasting a very short time.",
  },
  {
    id: "ver-007",
    category: "verbal",
    difficulty: 3,
    prompt: "Prudent is to reckless as generous is to:",
    answer: c(["Stingy", "Wealthy", "Kind", "Cautious"], 0),
    explanation: "Both pairs are opposites.",
  },
  {
    id: "ver-008",
    category: "verbal",
    difficulty: 3,
    prompt: "Which word is the odd one out?",
    answer: c(["Novel", "Sonnet", "Haiku", "Ode"], 0),
    explanation: "The other three are forms of poem.",
  },
  {
    id: "ver-009",
    category: "verbal",
    difficulty: 2,
    prompt: "Which word is the odd one out?",
    answer: c(["Shout", "Whisper", "Murmur", "Mumble"], 0),
    explanation: "The other three describe quiet speech.",
  },
  {
    id: "ver-010",
    category: "verbal",
    difficulty: 4,
    prompt: "'Laconic' most nearly means:",
    answer: c(
      ["Using very few words", "Deeply relaxed", "Openly rude", "Full of praise"],
      0,
    ),
    explanation: "A laconic speaker is terse to the point of bluntness.",
  },
  {
    id: "ver-011",
    category: "verbal",
    difficulty: 4,
    prompt: "Book is to chapter as symphony is to:",
    answer: c(["Movement", "Orchestra", "Composer", "Concert"], 0),
    explanation: "Both pairs relate a whole work to its major internal division.",
  },
  {
    id: "ver-012",
    category: "verbal",
    difficulty: 4,
    prompt:
      "'Obfuscate' is to 'clarify' as which pair below relate to one another?",
    answer: c(
      [
        "Conceal is to reveal",
        "Expand is to enlarge",
        "Begin is to start",
        "Murky is to opaque",
      ],
      0,
    ),
    explanation:
      "The stem pair are opposites; only 'conceal / reveal' is also an opposite pair.",
  },
  {
    id: "ver-013",
    category: "verbal",
    difficulty: 4,
    prompt: "'Intransigent' most nearly means:",
    answer: c(
      ["Refusing to compromise", "Easily persuaded", "Constantly moving", "Deeply confused"],
      0,
    ),
    explanation: "An intransigent person will not shift position.",
  },
  {
    id: "ver-014",
    category: "verbal",
    difficulty: 5,
    prompt: "'Sanguine' most nearly means:",
    answer: c(["Optimistic", "Bloodthirsty", "Exhausted", "Sceptical"], 0),
    explanation:
      "In modern usage sanguine means cheerfully confident about the future.",
  },
  {
    id: "ver-015",
    category: "verbal",
    difficulty: 5,
    prompt:
      "Choose the word that best completes the sentence: 'Her argument was ___; every objection had already been anticipated and answered.'",
    answer: c(["airtight", "tenuous", "verbose", "derivative"], 0),
    explanation:
      "The second clause describes an argument with no gaps, which is what 'airtight' means.",
  },
  {
    id: "ver-016",
    category: "verbal",
    difficulty: 1,
    prompt: "Puppy is to dog as kitten is to:",
    answer: c(["Cat", "Kennel", "Fur", "Mouse"], 0),
    explanation: "The relationship is 'young animal to adult animal'.",
  },
  {
    id: "ver-017",
    category: "verbal",
    difficulty: 3,
    prompt:
      "The letters H, E, L, W, A can be rearranged to spell the name of a:",
    answer: c(["Animal", "Fruit", "Country", "Tool"], 0),
    explanation: "The letters spell WHALE.",
  },
  {
    id: "ver-018",
    category: "verbal",
    difficulty: 4,
    prompt:
      "The letters N, I, P, S, A can be rearranged to spell the name of a:",
    answer: c(["Country", "Animal", "Fruit", "Metal"], 0),
    explanation: "The letters spell SPAIN.",
  },
  {
    id: "ver-019",
    category: "verbal",
    difficulty: 3,
    prompt: "Which word is the odd one out?",
    answer: c(["Granite", "Copper", "Iron", "Zinc"], 0),
    explanation: "The other three are metals; granite is a rock.",
  },
  {
    id: "ver-020",
    category: "verbal",
    difficulty: 4,
    prompt: "Nurture is to nature as learned is to:",
    answer: c(["Innate", "Studied", "Practised", "Forgotten"], 0),
    explanation:
      "Nurture pairs with what is acquired and nature with what is inborn.",
  },
  {
    id: "ver-021",
    category: "verbal",
    difficulty: 5,
    prompt: "'Perfunctory' most nearly means:",
    answer: c(
      ["Done without real care", "Perfectly executed", "Highly formal", "Unusually thorough"],
      0,
    ),
    explanation: "A perfunctory act is carried out as a routine minimum.",
  },
  {
    id: "ver-022",
    category: "verbal",
    difficulty: 3,
    prompt: "Drought is to water as famine is to:",
    answer: c(["Food", "Hunger", "Land", "Poverty"], 0),
    explanation: "Each pair names a shortage and the resource that is short.",
  },
  {
    id: "ver-023",
    category: "verbal",
    difficulty: 4,
    prompt: "'Assiduous' most nearly means:",
    answer: c(["Diligent", "Acidic", "Doubtful", "Assertive"], 0),
    explanation: "Assiduous describes constant, careful effort.",
  },
  {
    id: "ver-024",
    category: "verbal",
    difficulty: 5,
    prompt: "Which word is closest in meaning to 'ostensible'?",
    answer: c(["Apparent", "Showy", "Hostile", "Obsolete"], 0),
    explanation:
      "Ostensible means stated or appearing to be true, often as opposed to the real reason.",
  },
  {
    id: "ver-025",
    category: "verbal",
    difficulty: 2,
    prompt: "Which word is the odd one out?",
    answer: c(["Kettle", "Cup", "Mug", "Glass"], 0),
    explanation: "The other three are vessels you drink from.",
  },
  {
    id: "ver-026",
    category: "verbal",
    difficulty: 3,
    prompt: "Anchor is to ship as which word is to kite?",
    answer: c(["String", "Wind", "Sky", "Tail"], 0),
    explanation: "Both tether the object and stop it drifting away.",
  },
  {
    id: "ver-027",
    category: "verbal",
    difficulty: 5,
    prompt: "To 'equivocate' is to:",
    answer: c(
      [
        "Speak ambiguously to avoid committing yourself",
        "Argue both sides of a case fairly",
        "Correct an earlier mistake",
        "Treat two people as equals",
      ],
      0,
    ),
    explanation:
      "Equivocation uses deliberately unclear language to dodge commitment.",
  },
  {
    id: "ver-028",
    category: "verbal",
    difficulty: 1,
    prompt: "Which word means the opposite of 'ascend'?",
    answer: c(["Descend", "Arrive", "Expand", "Hasten"], 0),
    explanation: "Ascend means to go up; descend means to go down.",
  },
  {
    id: "ver-029",
    category: "verbal",
    difficulty: 2,
    prompt: "Author is to novel as composer is to:",
    answer: c(["Symphony", "Orchestra", "Piano", "Audience"], 0),
    explanation: "Each pair links a creator to the work they produce.",
  },
  {
    id: "ver-030",
    category: "verbal",
    difficulty: 3,
    prompt: "Which word is the odd one out?",
    answer: c(["Flute", "Violin", "Cello", "Viola"], 0),
    explanation: "The other three are string instruments; the flute is a wind instrument.",
  },
  {
    id: "ver-031",
    category: "verbal",
    difficulty: 3,
    prompt: "'Meticulous' most nearly means:",
    answer: c(["Extremely careful about detail", "Unusually slow", "Openly critical", "Highly ambitious"], 0),
    explanation: "Meticulous work shows precise attention to every detail.",
  },
  {
    id: "ver-032",
    category: "verbal",
    difficulty: 4,
    prompt: "'Tacit' most nearly means:",
    answer: c(["Understood without being stated", "Deliberately rude", "Firmly held", "Easily broken"], 0),
    explanation: "A tacit agreement is implied rather than spoken.",
  },
  {
    id: "ver-033",
    category: "verbal",
    difficulty: 1,
    prompt: "Which word is most nearly the opposite of 'expand'?",
    answer: c(["Contract", "Extend", "Elevate", "Divide"], 0),
    explanation: "To expand is to grow larger; to contract is to shrink.",
  },
  {
    id: "ver-034",
    category: "verbal",
    difficulty: 2,
    prompt: "Caterpillar is to butterfly as tadpole is to:",
    answer: c(["Frog", "Pond", "Fish", "Egg"], 0),
    explanation: "Each pair links a juvenile form to the adult it becomes.",
  },
  {
    id: "ver-035",
    category: "verbal",
    difficulty: 4,
    prompt: "'Ubiquitous' most nearly means:",
    answer: c(["Found everywhere", "Extremely rare", "Widely admired", "Hard to explain"], 0),
    explanation: "Something ubiquitous is present in all places at once.",
  },
  {
    id: "ver-036",
    category: "verbal",
    difficulty: 5,
    prompt: "'Recalcitrant' most nearly means:",
    answer: c(["Stubbornly resistant to authority", "Slow to recover", "Quick to apologise", "Prone to miscalculation"], 0),
    explanation: "A recalcitrant person refuses to be managed or persuaded.",
  },
  {
    id: "ver-037",
    category: "verbal",
    difficulty: 3,
    prompt: "Which word is the odd one out?",
    answer: c(["Litre", "Mile", "Metre", "Inch"], 0),
    explanation: "The other three measure length; a litre measures volume.",
  },
  {
    id: "ver-038",
    category: "verbal",
    difficulty: 4,
    prompt: "Famine is to food as insomnia is to:",
    answer: c(["Sleep", "Night", "Fatigue", "Illness"], 0),
    explanation: "Each pair names a condition and the thing it deprives you of.",
  },
  {
    id: "ver-039",
    category: "verbal",
    difficulty: 5,
    prompt: "'Pellucid' most nearly means:",
    answer: c(["Perfectly clear", "Faintly coloured", "Deeply persuasive", "Slow-moving"], 0),
    explanation: "Pellucid describes something transparent, literally or in expression.",
  },
  {
    id: "ver-040",
    category: "verbal",
    difficulty: 1,
    prompt: "Which word is most nearly the opposite of 'temporary'?",
    answer: c(["Permanent", "Immediate", "Fragile", "Occasional"], 0),
    explanation: "Temporary means lasting only a limited time.",
  },
  {
    id: "ver-041",
    category: "verbal",
    difficulty: 4,
    prompt: "Scaffolding is to building as which word is to argument?",
    answer: c(["Premise", "Conclusion", "Rebuttal", "Opinion"], 0),
    explanation: "Scaffolding supports a building while it stands up; premises support an argument.",
  },
  {
    id: "ver-042",
    category: "verbal",
    difficulty: 2,
    prompt: "Which word is the odd one out?",
    answer: c(["Patient", "Doctor", "Surgeon", "Dentist"], 0),
    explanation: "The other three are medical practitioners.",
  },
  {
    id: "ver-043",
    category: "verbal",
    difficulty: 5,
    prompt: "'Inchoate' most nearly means:",
    answer: c(["Just begun and not fully formed", "Impossible to understand", "Deeply traditional", "Beyond repair"], 0),
    explanation: "An inchoate plan exists only in rudimentary form.",
  },
  {
    id: "ver-044",
    category: "verbal",
    difficulty: 3,
    prompt: "The letters R, B, Z, E and A can be rearranged to spell the name of a:",
    answer: c(["Animal", "Country", "Vegetable", "Tool"], 0),
    explanation: "The letters spell ZEBRA.",
  },
  {
    id: "ver-045",
    category: "verbal",
    difficulty: 4,
    prompt: "The letters L, C, N, I, E and P can be rearranged to spell a:",
    answer: c(["Writing implement", "Sea creature", "Musical instrument", "Item of clothing"], 0),
    explanation: "The letters spell PENCIL.",
  },
  {
    id: "ver-046",
    category: "verbal",
    difficulty: 4,
    prompt: "To 'ameliorate' something is to:",
    answer: c(["Make it better", "Make it official", "Break it apart", "Put it off"], 0),
    explanation: "Amelioration improves a bad situation.",
  },
  {
    id: "ver-047",
    category: "verbal",
    difficulty: 1,
    prompt: "Which word is closest in meaning to 'brief'?",
    answer: c(["Concise", "Urgent", "Simple", "Formal"], 0),
    explanation: "Both describe something short in length or duration.",
  },
  {
    id: "ver-048",
    category: "verbal",
    difficulty: 5,
    prompt: "Choose the word that best completes the sentence: 'The evidence was ___: it neither confirmed the hypothesis nor ruled it out.'",
    answer: c(["inconclusive", "overwhelming", "fabricated", "circumstantial"], 0),
    explanation: "The clause describes evidence that settles nothing either way.",
  },
  {
    id: "ver-049",
    category: "verbal",
    difficulty: 3,
    prompt: "Herd is to cattle as which word is to fish?",
    answer: c(["School", "Flock", "Pack", "Swarm"], 0),
    explanation: "Each is the collective noun for the animal named.",
  },
  {
    id: "ver-050",
    category: "verbal",
    difficulty: 4,
    prompt: "'Gregarious' most nearly means:",
    answer: c(["Sociable", "Greedy", "Argumentative", "Generous"], 0),
    explanation: "A gregarious person seeks and enjoys the company of others.",
  },
];
